# Generated by Django 5.2.15 on 2026-06-17 22:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "occurred_at",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("buy", "買い"),
                            ("sell", "売り"),
                            ("hold", "ホールド"),
                            ("watch", "ウォッチ"),
                            ("note", "メモ"),
                        ],
                        default="note",
                        max_length=8,
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=20)),
                ("instrument_name", models.CharField(blank=True, max_length=120)),
                ("hypothesis", models.TextField(blank=True, verbose_name="仮説")),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="確信度"
                    ),
                ),
                (
                    "falsification",
                    models.TextField(blank=True, verbose_name="反証条件"),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("unverified", "未検証"),
                            ("hit", "当たった"),
                            ("miss", "外れた"),
                            ("partial", "部分的"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=12,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("learning", models.TextField(blank=True, verbose_name="学び")),
                (
                    "learning_confidence_calibration",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("published", "記録済み")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "記録",
                "verbose_name_plural": "記録",
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ThemeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=60)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EntryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="journal.entry"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.themetag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="entries",
                through="journal.EntryTag",
                to="journal.themetag",
            ),
        ),
        migrations.CreateModel(
            name="TradeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("realized", models.BooleanField(default=False)),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "pnl_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "pnl_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="journal.entry",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "結果",
                "verbose_name_plural": "結果",
            },
        ),
        migrations.AddConstraint(
            model_name="themetag",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="uniq_owner_tag_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrytag",
            constraint=models.UniqueConstraint(
                fields=("entry", "tag"), name="uniq_entry_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["owner", "occurred_at"], name="journal_ent_owner_i_493366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["owner", "verdict", "status"],
                name="journal_ent_owner_i_a466c9_idx",
            ),
        ),
    ]
