# Generated by Django 5.2.15 on 2026-06-18 00:36

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        # Enable the pgvector extension before adding the vector column.
        VectorExtension(),
        migrations.AddField(
            model_name="entry",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, editable=False, null=True
            ),
        ),
    ]
