# Generated by Django 5.2.15 on 2026-06-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallShownLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=24)),
                ("shown_on", models.DateField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("shown", "表示"),
                            ("opened", "開いた"),
                            ("dismissed", "あとで"),
                            ("acted", "対応済"),
                        ],
                        default="shown",
                        max_length=10,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recall_shows",
                        to="journal.entry",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "entry", "source", "shown_on"],
                        name="recall_reca_owner_i_7f7b4e_idx",
                    )
                ],
            },
        ),
    ]
